service: restaurant-marketplace-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - Fn::GetAtt: [PurchaseHistoryTable, Arn]
            - Fn::Join:
                - '/'
                - - Fn::GetAtt: [PurchaseHistoryTable, Arn]
                  - 'index/*'

custom:
  httpApi:
    cors:
      allowedOrigins:
        - "http://localhost:3000"
        - "https://*.vercel.app"
        - "https://*.netlify.app"
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Requested-With
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: true

functions:
  web:
    handler: public/index.php
    timeout: 60
    memorySize: 1024
    layers:
      - ${bref:layer.php-82-fpm}
    environment:
      BREF_BINARY_RESPONSES: 1
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:alV9TLgsKZ+PSgRqizZLs8xEElTVVEvHj6wNK4hWu/M=

      DB_CONNECTION: array
      DYNAMODB_TABLE: restaurant-purchases-${self:provider.stage}

      CACHE_DRIVER: array
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync
      LOG_CHANNEL: stderr

      ORDER_SERVICE_URL: https://hkg61nbow3.execute-api.us-east-1.amazonaws.com
      KITCHEN_SERVICE_URL: https://pgvdivqhbi.execute-api.us-east-1.amazonaws.com
      WAREHOUSE_SERVICE_URL: https://0fntnq3zqe.execute-api.us-east-1.amazonaws.com
      MARKETPLACE_SERVICE_URL: https://3euu6m4xs6.execute-api.us-east-1.amazonaws.com
      FARMERS_MARKET_API: https://recruitment.alegra.com/api/farmers-market/buy

    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY

  artisan:
    handler: artisan
    timeout: 120
    layers:
      - ${bref:layer.php-82}
      - ${bref:layer.console}
    environment:
      APP_ENV: production
      APP_KEY: base64:alV9TLgsKZ+PSgRqizZLs8xEElTVVEvHj6wNK4hWu/M=
      DB_CONNECTION: array
      DYNAMODB_TABLE: restaurant-purchases-${self:provider.stage}

resources:
  Resources:
    PurchaseHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: restaurant-purchases-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: order_id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: order-lookup-gsi
            KeySchema:
              - AttributeName: order_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: false

  Outputs:
    MarketplaceServiceUrl:
      Description: "Marketplace Service API URL"
      Value:
        Fn::Join:
          - ''
          - - 'https://'
            - Ref: HttpApi
            - '.execute-api.'
            - ${self:provider.region}
            - '.amazonaws.com'
      Export:
        Name: MarketplaceServiceUrl-${self:provider.stage}

plugins:
  - ./vendor/bref/bref